http://localhost:4000/
###

http://localhost:4000/blocks
###

POST http://localhost:4000/blocks

{
    "message": "Data for my block"
}
###

http://localhost:4000/blocks/b184f1892bd61af30b086a1aa3af99c133aad8e555f1f491d117d9d60a6a36c9